export type Member = {
    userNo : number,
	statusType : number,
	positionNo : number,
	deptNo : number,
	totalLeaveDays : number,
	eNo : number,
	status : string,
	profileImg : string,
	userPwd : string,
	userName : string,
	phone : string,
	extension : string,
	email : string,
	address : string,
	hireDate : string,
	updateDate : string,
}